"""
seed_medicines.py — Run this ONCE to populate the medicines table.
Usage (from the backend/ directory):
    python seed_medicines.py
"""

import asyncio
from database import engine, Base
from models import Medicine
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import sessionmaker
from sqlalchemy import select

AsyncSessionLocal = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

MEDICINES = [
    # ─────────────────────────────────────────────────────────────
    # PAIN RELIEF & FEVER
    # ─────────────────────────────────────────────────────────────
    {
        "name": "Paracetamol (Acetaminophen)",
        "brand_names": "Crocin, Dolo 650, Calpol, Panadol, Tylenol, Metacin",
        "category": "Pain Relief & Fever",
        "medicine_type": "Tablet / Syrup",
        "active_ingredients": "Paracetamol 500mg or 650mg",
        "uses": "Relieves mild to moderate pain (headache, toothache, body ache, period pain). Reduces fever (antipyretic).",
        "side_effects": "Rare at normal doses. Overdose can cause serious liver damage. Nausea, rash in rare cases.",
        "dosage": "Adults: 500mg–1000mg every 4–6 hours. Max 4g/day. Children: weight-based — consult a doctor.",
        "precautions": "Do not exceed the recommended dose. Avoid alcohol. Use cautiously in liver disease.",
        "contraindications": "Severe liver disease. Allergy to paracetamol.",
        "is_otc": True,
        "emoji": "💊",
    },
    {
        "name": "Ibuprofen",
        "brand_names": "Brufen, Advil, Nurofen, Combiflam (with Paracetamol)",
        "category": "Pain Relief & Fever",
        "medicine_type": "Tablet / Syrup",
        "active_ingredients": "Ibuprofen 200mg, 400mg, or 600mg",
        "uses": "Relieves pain, fever, and inflammation. Used for headache, toothache, menstrual cramps, arthritis, muscle aches.",
        "side_effects": "Stomach upset, heartburn, nausea, dizziness. Long-term use: ulcers, kidney stress, increased blood pressure risk.",
        "dosage": "Adults: 200–400mg every 4–6 hours with food. Max 1200mg/day (OTC). Children: weight-based.",
        "precautions": "Always take with food. Avoid on an empty stomach. Avoid if you have a history of ulcers.",
        "contraindications": "Active stomach ulcer, severe kidney or liver disease, last trimester of pregnancy, heart failure.",
        "is_otc": True,
        "emoji": "💊",
    },
    {
        "name": "Aspirin",
        "brand_names": "Disprin, Ecosprin, Aspro",
        "category": "Pain Relief & Fever",
        "medicine_type": "Tablet",
        "active_ingredients": "Acetylsalicylic acid 75mg, 325mg, or 650mg",
        "uses": "Relieves mild to moderate pain and fever. Low-dose (75mg) used daily to prevent heart attacks and strokes (antiplatelet).",
        "side_effects": "Stomach irritation, bleeding risk, nausea. Can cause Reye's syndrome in children.",
        "dosage": "Pain/Fever: 325–650mg every 4–6 hours. Heart protection: 75–100mg once daily (prescribed by doctor).",
        "precautions": "Take with food or milk. Avoid if you have a bleeding disorder.",
        "contraindications": "Children under 16 years (Reye's syndrome risk), bleeding disorders, active peptic ulcer.",
        "is_otc": True,
        "emoji": "💊",
    },
    {
        "name": "Diclofenac",
        "brand_names": "Voveran, Voltaren, Diclogesic, Reactine",
        "category": "Pain Relief & Fever",
        "medicine_type": "Tablet / Gel / Injection",
        "active_ingredients": "Diclofenac Sodium 50mg, 75mg, 100mg",
        "uses": "Relieves moderate to severe pain and inflammation. Used for arthritis, back pain, sprains, sports injuries, period pain.",
        "side_effects": "Stomach pain, heartburn, nausea, headache. Long-term: ulcers, kidney problems, raised blood pressure.",
        "dosage": "50mg two to three times daily with food. Gel applied directly 3–4 times per day.",
        "precautions": "Take with food. Avoid long-term use without medical supervision.",
        "contraindications": "Active peptic ulcer, severe kidney/heart/liver failure, third trimester of pregnancy.",
        "is_otc": False,
        "emoji": "💊",
    },
    {
        "name": "Naproxen",
        "brand_names": "Naprosyn, Aleve",
        "category": "Pain Relief & Fever",
        "medicine_type": "Tablet",
        "active_ingredients": "Naproxen 250mg, 500mg",
        "uses": "Treats pain, inflammation, and fever. Used for arthritis, menstrual cramps, tendinitis, gout.",
        "side_effects": "Stomach upset, nausea, headache, dizziness, heartburn.",
        "dosage": "Adults: 250–500mg twice daily with food. Max 1250mg/day.",
        "precautions": "Take with food. Avoid alcohol. Use lowest effective dose.",
        "contraindications": "Active ulcer, severe kidney/heart disease, third trimester of pregnancy.",
        "is_otc": False,
        "emoji": "💊",
    },
    {
        "name": "Aceclofenac",
        "brand_names": "Aceclo, Hifenac, Zerodol",
        "category": "Pain Relief & Fever",
        "medicine_type": "Tablet",
        "active_ingredients": "Aceclofenac 100mg",
        "uses": "Relieves pain and inflammation in arthritis, back pain, joint pain, dental pain, and post-operative pain.",
        "side_effects": "Nausea, stomach pain, indigestion, diarrhea, dizziness.",
        "dosage": "100mg twice daily with food. Take after meals.",
        "precautions": "Avoid empty stomach. Use with caution in elderly patients.",
        "contraindications": "Peptic ulcer, severe liver/kidney disease, last trimester of pregnancy.",
        "is_otc": False,
        "emoji": "💊",
    },

    # ─────────────────────────────────────────────────────────────
    # FIRST AID & ANTISEPTICS
    # ─────────────────────────────────────────────────────────────
    {
        "name": "Dettol Antiseptic Liquid",
        "brand_names": "Dettol",
        "category": "First Aid & Antiseptics",
        "medicine_type": "Topical Liquid",
        "active_ingredients": "Chloroxylenol (PCMX) 4.8%",
        "uses": "Kills bacteria and germs on skin. Used for wound cleaning, cuts, abrasions, insect bites, minor burns. Also used to disinfect surfaces.",
        "side_effects": "Skin irritation or allergy in sensitive individuals. Toxic if swallowed.",
        "dosage": "Dilute 1 capful in a cup of water for wound cleaning. Apply with cotton wool. Do NOT use undiluted on skin.",
        "precautions": "Always dilute before applying to skin. Keep away from eyes. Do not swallow.",
        "contraindications": "Do not use in eyes or ears. Not for deep wounds or serious burns.",
        "is_otc": True,
        "emoji": "🧴",
    },
    {
        "name": "Betadine (Povidone-Iodine)",
        "brand_names": "Betadine, Wokadine, Isodine",
        "category": "First Aid & Antiseptics",
        "medicine_type": "Topical Liquid / Ointment",
        "active_ingredients": "Povidone-Iodine 5% or 10%",
        "uses": "Broad-spectrum antiseptic. Used for wound disinfection, pre-surgical skin prep, infected wounds, mouth ulcers (gargle form).",
        "side_effects": "Skin irritation, staining (brown color), allergic reaction. Thyroid disruption with long-term large-area use.",
        "dosage": "Apply directly to wound or dilute with water (1:10) for gargling. Use once or twice daily.",
        "precautions": "Avoid prolonged use on large areas. Wash off after use. Can stain fabric.",
        "contraindications": "Iodine allergy, thyroid disorders, pregnancy/breastfeeding (large areas), newborns.",
        "is_otc": True,
        "emoji": "🩹",
    },
    {
        "name": "Savlon Antiseptic",
        "brand_names": "Savlon",
        "category": "First Aid & Antiseptics",
        "medicine_type": "Topical Liquid / Cream",
        "active_ingredients": "Chlorhexidine Gluconate 1.5% + Cetrimide 15%",
        "uses": "Disinfects and cleans minor cuts, grazes, and wounds. Gentler than Dettol on skin. Also used for skin cleansing before injections.",
        "side_effects": "Mild skin irritation. Rare allergic reactions.",
        "dosage": "Dilute 1 part Savlon in 30 parts water for wound cleaning. Apply with cotton swab. Cream can be applied directly.",
        "precautions": "Do not use in eyes. Do not swallow. Rinse wound with clean water first.",
        "contraindications": "Allergy to chlorhexidine.",
        "is_otc": True,
        "emoji": "🧴",
    },
    {
        "name": "Hydrogen Peroxide",
        "brand_names": "H2O2 Solution (3%)",
        "category": "First Aid & Antiseptics",
        "medicine_type": "Topical Solution",
        "active_ingredients": "Hydrogen Peroxide 3%",
        "uses": "Cleaning and disinfecting minor wounds, cuts, and abrasions. Removes earwax (ear drops). Teeth whitening mouthwash (diluted).",
        "side_effects": "Foaming on wounds (normal), stinging sensation, skin/tissue bleaching. Can delay wound healing with repeated use.",
        "dosage": "Apply 3% solution directly to wound using cotton. Use sparingly — once per wound event is usually enough.",
        "precautions": "Do not use on deep wounds, puncture wounds, or serious burns. Avoid contact with eyes.",
        "contraindications": "Deep wounds, animal bites (seek medical care). Higher concentrations (>3%) are dangerous.",
        "is_otc": True,
        "emoji": "💧",
    },
    {
        "name": "Adhesive Bandages (Band-Aid / Plasters)",
        "brand_names": "Band-Aid, Hansaplast, Dressit",
        "category": "First Aid & Antiseptics",
        "medicine_type": "Dressing",
        "active_ingredients": "Non-medicated: sterile absorbent pad, adhesive. Some medicated variants contain antiseptic.",
        "uses": "Covering and protecting minor cuts, scrapes, blisters, and abrasions from dirt and infection.",
        "side_effects": "Skin irritation or allergic reaction from adhesive in sensitive individuals.",
        "dosage": "Clean wound thoroughly. Apply one plaster over the wound, sticky side to skin. Change daily or when wet/dirty.",
        "precautions": "Ensure wound is clean before applying. Do not apply to infected wounds. Change regularly.",
        "contraindications": "Not for large or deep wounds — seek medical attention.",
        "is_otc": True,
        "emoji": "🩹",
    },
    {
        "name": "Zinc Oxide Bandage / Crepe Bandage",
        "brand_names": "Elastoplast, Steroplast",
        "category": "First Aid & Antiseptics",
        "medicine_type": "Bandage / Dressing",
        "active_ingredients": "Cotton / elastic fibers. Zinc oxide in medicated variants.",
        "uses": "Providing support and compression for sprains, strains, and fractures. Holding dressings in place.",
        "side_effects": "Improper wrapping can restrict blood flow. Skin irritation with zinc oxide.",
        "dosage": "Wrap around injured area with moderate tension. Not too tight — fingers/toes should remain warm and able to move.",
        "precautions": "Check circulation frequently after bandaging. Rewrap every 8 hours.",
        "contraindications": "Do not wrap too tightly. Not a substitute for a cast in fractures.",
        "is_otc": True,
        "emoji": "🩹",
    },
    {
        "name": "Calamine Lotion",
        "brand_names": "Lacto Calamine, Caladryl",
        "category": "First Aid & Antiseptics",
        "medicine_type": "Topical Lotion",
        "active_ingredients": "Calamine (Zinc Oxide + Ferric Oxide) 15%, Glycerin",
        "uses": "Soothes itching and irritation from insect bites, rashes, hives, sunburn, chickenpox, and prickly heat.",
        "side_effects": "Very well tolerated. Rare: skin dryness or mild irritation.",
        "dosage": "Shake well. Apply liberally to affected area 3–4 times per day and let it dry. Repeat as needed.",
        "precautions": "Keep away from eyes and mouth. External use only.",
        "contraindications": "Allergy to zinc oxide.",
        "is_otc": True,
        "emoji": "🧴",
    },

    # ─────────────────────────────────────────────────────────────
    # COLD, COUGH & FLU
    # ─────────────────────────────────────────────────────────────
    {
        "name": "Cetirizine",
        "brand_names": "Zyrtec, Alerid, Cetzine, L-Cet",
        "category": "Cold, Cough & Allergy",
        "medicine_type": "Tablet / Syrup",
        "active_ingredients": "Cetirizine Hydrochloride 10mg",
        "uses": "Relieves symptoms of allergic rhinitis (hay fever), urticaria (hives), watery eyes, runny nose, sneezing, and skin allergies.",
        "side_effects": "Drowsiness (less than older antihistamines), dry mouth, headache, fatigue.",
        "dosage": "Adults: 10mg once daily at bedtime. Children 6–12 years: 5mg once daily.",
        "precautions": "May cause drowsiness — avoid driving or operating machinery. Avoid alcohol.",
        "contraindications": "Severe kidney disease. Allergy to cetirizine or hydroxyzine.",
        "is_otc": True,
        "emoji": "🤧",
    },
    {
        "name": "Loratadine",
        "brand_names": "Claritin, Lorfast, Clarityn",
        "category": "Cold, Cough & Allergy",
        "medicine_type": "Tablet",
        "active_ingredients": "Loratadine 10mg",
        "uses": "Non-drowsy antihistamine. Relieves allergy symptoms: sneezing, runny nose, itchy eyes, skin rashes.",
        "side_effects": "Headache, dry mouth, fatigue. Rarely causes drowsiness.",
        "dosage": "Adults and children over 12: 10mg once daily.",
        "precautions": "Preferred antihistamine when you cannot afford to feel drowsy.",
        "contraindications": "Allergy to loratadine. Use caution in liver disease.",
        "is_otc": True,
        "emoji": "🤧",
    },
    {
        "name": "Dextromethorphan (Cough Suppressant)",
        "brand_names": "Benylin DM, Robitussin DM, Kofarest",
        "category": "Cold, Cough & Allergy",
        "medicine_type": "Syrup / Tablet",
        "active_ingredients": "Dextromethorphan HBr 15mg per 5ml",
        "uses": "Suppresses a dry, tickly, non-productive cough. Does NOT help productive (wet/phlegmy) coughs.",
        "side_effects": "Dizziness, drowsiness, nausea, constipation.",
        "dosage": "Adults: 10–20ml (30mg) every 4 hours. Do not exceed 120mg/day.",
        "precautions": "Do not use for more than 7 days without seeing a doctor. Do not use for productive coughs.",
        "contraindications": "Do not take with MAO inhibitors (antidepressants). Children under 4 years.",
        "is_otc": True,
        "emoji": "🤧",
    },
    {
        "name": "Ambroxol / Bromhexine (Expectorant)",
        "brand_names": "Mucinac, Ambrolite, Mucosolvan, Alex",
        "category": "Cold, Cough & Allergy",
        "medicine_type": "Syrup / Tablet",
        "active_ingredients": "Ambroxol HCl 30mg or Bromhexine 8mg",
        "uses": "Loosens and thins mucus (phlegm) to make wet coughs more productive and easier to clear.",
        "side_effects": "Nausea, stomach upset, vomiting, diarrhea.",
        "dosage": "Adults: 30mg (Ambroxol) 3 times daily. Take with plenty of fluids.",
        "precautions": "Drink plenty of water while taking. Not effective for dry coughs.",
        "contraindications": "Active stomach ulcer. First trimester of pregnancy.",
        "is_otc": True,
        "emoji": "🤧",
    },
    {
        "name": "Xylometazoline Nasal Drops",
        "brand_names": "Otrivin, Nasivion, Xylomist",
        "category": "Cold, Cough & Allergy",
        "medicine_type": "Nasal Drops / Spray",
        "active_ingredients": "Xylometazoline HCl 0.05% (children) / 0.1% (adults)",
        "uses": "Instantly relieves nasal congestion (blocked nose) caused by cold, sinusitis, or allergies.",
        "side_effects": "Temporary stinging or burning in the nose. Rebound congestion if used for more than 3 days.",
        "dosage": "2–3 drops in each nostril, 2–3 times daily for a maximum of 3 days.",
        "precautions": "Do NOT use for more than 3 consecutive days — causes rebound (worse) congestion.",
        "contraindications": "Narrow-angle glaucoma, high blood pressure, heart disease, hyperthyroidism.",
        "is_otc": True,
        "emoji": "👃",
    },

    # ─────────────────────────────────────────────────────────────
    # DIGESTIVE HEALTH
    # ─────────────────────────────────────────────────────────────
    {
        "name": "Omeprazole",
        "brand_names": "Omez, Prilosec, Losec",
        "category": "Digestive Health",
        "medicine_type": "Capsule",
        "active_ingredients": "Omeprazole 20mg or 40mg",
        "uses": "Reduces stomach acid. Used for acid reflux (GERD), peptic ulcers, heartburn, and stomach protection when taking NSAIDs.",
        "side_effects": "Headache, nausea, diarrhea, stomach pain. Long-term: low magnesium, Vitamin B12 deficiency.",
        "dosage": "20mg once daily before breakfast. For ulcers: 20–40mg once daily for 4–8 weeks.",
        "precautions": "Take 30–60 minutes before eating. Long-term use should be under medical supervision.",
        "contraindications": "Allergy to omeprazole or other PPIs.",
        "is_otc": False,
        "emoji": "💊",
    },
    {
        "name": "Pantoprazole",
        "brand_names": "Pan-D, Pantocid, Protonix",
        "category": "Digestive Health",
        "medicine_type": "Tablet",
        "active_ingredients": "Pantoprazole 40mg",
        "uses": "Reduces excess stomach acid. Used for acid reflux, GERD, peptic ulcers, Zollinger-Ellison syndrome.",
        "side_effects": "Headache, diarrhea, nausea, stomach pain.",
        "dosage": "40mg once daily before breakfast.",
        "precautions": "Swallow whole — do not crush or chew. Take before meals.",
        "contraindications": "Allergy to pantoprazole.",
        "is_otc": False,
        "emoji": "💊",
    },
    {
        "name": "Antacid (Aluminium + Magnesium Hydroxide)",
        "brand_names": "Gelusil, Digene, Eno (Sodium Bicarbonate), Kremil-S",
        "category": "Digestive Health",
        "medicine_type": "Tablet / Syrup / Powder",
        "active_ingredients": "Aluminium Hydroxide + Magnesium Hydroxide (in tablets). Sodium Bicarbonate + Citric Acid (ENO).",
        "uses": "Quick relief of heartburn, acidity, indigestion, stomach upset, and gas.",
        "side_effects": "Constipation (aluminium), diarrhea (magnesium). Rebound acidity with prolonged use.",
        "dosage": "1–2 tablets or 10ml syrup after meals and at bedtime. ENO: 1 sachet dissolved in water.",
        "precautions": "Short-term use only. Take 2 hours away from other medicines (reduces absorption).",
        "contraindications": "Kidney disease (Aluminium/Magnesium types). Low sodium diet (ENO/Sodium Bicarb).",
        "is_otc": True,
        "emoji": "🫃",
    },
    {
        "name": "ORS — Oral Rehydration Salts",
        "brand_names": "Electral, Pedialyte, WHO-ORS, Walyte",
        "category": "Digestive Health",
        "medicine_type": "Powder (dissolved in water)",
        "active_ingredients": "Sodium Chloride, Potassium Chloride, Sodium Citrate, Glucose",
        "uses": "Replaces fluids and electrolytes lost during diarrhea, vomiting, dehydration from illness, heatstroke, or intense exercise.",
        "side_effects": "Safe for all ages. Rarely: nausea if drunk too fast. High sodium can be an issue with severe kidney disease.",
        "dosage": "Dissolve 1 sachet in 1 litre of clean water. Drink small sips frequently. Adults: 200–400ml after each loose stool.",
        "precautions": "Use fresh clean water. Discard prepared solution after 1 hour at room temperature or refrigerate for up to 24 hours.",
        "contraindications": "Severe dehydration with vomiting (IV fluids needed). Intestinal blockage.",
        "is_otc": True,
        "emoji": "💧",
    },
    {
        "name": "Domperidone",
        "brand_names": "Vomistop, Domstal, Motilium",
        "category": "Digestive Health",
        "medicine_type": "Tablet / Syrup",
        "active_ingredients": "Domperidone 10mg",
        "uses": "Relieves nausea and vomiting. Also helps with bloating, discomfort, and feeling of fullness after eating (gastroparesis).",
        "side_effects": "Dry mouth, headache, rarely: cardiac rhythm changes (with high doses).",
        "dosage": "10mg three times daily 30 minutes before meals. Maximum 3 days for nausea/vomiting.",
        "precautions": "Do not exceed recommended dose or duration. Not for long-term use without prescription.",
        "contraindications": "Cardiac problems (QT prolongation), pituitary tumor, liver disease.",
        "is_otc": False,
        "emoji": "🤢",
    },
    {
        "name": "Ondansetron",
        "brand_names": "Emeset, Zofran, Ondem",
        "category": "Digestive Health",
        "medicine_type": "Tablet / Injection",
        "active_ingredients": "Ondansetron 4mg or 8mg",
        "uses": "Powerful antiemetic. Prevents nausea and vomiting caused by chemotherapy, surgery, radiation, or severe gastroenteritis.",
        "side_effects": "Headache, constipation, dizziness, fatigue.",
        "dosage": "4–8mg 30 minutes before chemotherapy or 8mg every 12 hours. Oral dissolving tablets placed on tongue.",
        "precautions": "Can cause QT prolongation — use with caution in heart conditions.",
        "contraindications": "Known QT prolongation syndrome. Allergy to ondansetron.",
        "is_otc": False,
        "emoji": "🤢",
    },
    {
        "name": "Loperamide",
        "brand_names": "Imodium, Eldoper, Normode",
        "category": "Digestive Health",
        "medicine_type": "Capsule",
        "active_ingredients": "Loperamide HCl 2mg",
        "uses": "Reduces the frequency of diarrhea by slowing intestinal movement. Used for acute and chronic diarrhea.",
        "side_effects": "Constipation, abdominal cramps, dizziness, nausea.",
        "dosage": "Adults: 4mg initially, then 2mg after each loose stool. Max 16mg/day. Children: doctor's guidance only.",
        "precautions": "Do not use if you have bloody diarrhea or fever. Drink plenty of fluids.",
        "contraindications": "Bloody diarrhea, bacterial enterocolitis, pseudomembranous colitis. Children under 12.",
        "is_otc": True,
        "emoji": "💊",
    },
    {
        "name": "Isabgol (Psyllium Husk)",
        "brand_names": "Sat Isabgol, Metamucil, Fybogel, Ispaghula",
        "category": "Digestive Health",
        "medicine_type": "Powder / Husk",
        "active_ingredients": "Psyllium Husk (100% natural fiber)",
        "uses": "Relieves constipation by absorbing water and forming a gel. Also reduces cholesterol, helps with irritable bowel syndrome (IBS).",
        "side_effects": "Bloating, gas (especially initially). Can cause choking if not taken with enough water.",
        "dosage": "1–2 teaspoons in a full glass (240ml) of water, 1–3 times daily. Drink immediately.",
        "precautions": "MUST be taken with a full glass of water. Do not take at bedtime.",
        "contraindications": "Difficulty swallowing, intestinal blockage. Take 2 hours away from other medications.",
        "is_otc": True,
        "emoji": "🌿",
    },
    {
        "name": "Bisacodyl",
        "brand_names": "Dulcolax, Laxoberon, Bisakind",
        "category": "Digestive Health",
        "medicine_type": "Tablet / Suppository",
        "active_ingredients": "Bisacodyl 5mg (tablets), 10mg (suppository)",
        "uses": "Stimulant laxative for short-term relief of constipation. Also used to empty bowels before a colonoscopy.",
        "side_effects": "Abdominal cramps, nausea, diarrhea. Long-term use depletes electrolytes.",
        "dosage": "Tablets: 5–10mg at bedtime (works in 6–12 hours). Suppository: 10mg in the morning.",
        "precautions": "Do not crush/chew tablets. Do not take with milk or antacids (removes coating). Short-term use only.",
        "contraindications": "Intestinal obstruction, appendicitis, IBD, severe abdominal pain of unknown cause.",
        "is_otc": True,
        "emoji": "💊",
    },

    # ─────────────────────────────────────────────────────────────
    # ANTIBIOTICS
    # ─────────────────────────────────────────────────────────────
    {
        "name": "Amoxicillin",
        "brand_names": "Novamox, Mox, Trimox, Amoxil",
        "category": "Antibiotics",
        "medicine_type": "Capsule / Syrup",
        "active_ingredients": "Amoxicillin 250mg, 500mg",
        "uses": "Broad-spectrum penicillin antibiotic. Treats ear infections, throat infections (strep throat), chest infections, UTIs, skin infections, dental infections.",
        "side_effects": "Nausea, diarrhea, rash, vomiting. Rare: severe allergic reaction (anaphylaxis).",
        "dosage": "Adults: 250–500mg every 8 hours for 5–7 days. Children: weight-based (25mg/kg/day). Take with or without food.",
        "precautions": "Complete the full course even if you feel better. Tell your doctor about any penicillin allergy.",
        "contraindications": "Penicillin allergy, glandular fever (causes rash).",
        "is_otc": False,
        "emoji": "💊",
    },
    {
        "name": "Azithromycin",
        "brand_names": "Azithral, Zithromax, Azifast, Z-pak",
        "category": "Antibiotics",
        "medicine_type": "Tablet",
        "active_ingredients": "Azithromycin 250mg or 500mg",
        "uses": "Macrolide antibiotic. Treats respiratory infections, typhoid fever, pneumonia, sinusitis, skin infections, sexually transmitted infections.",
        "side_effects": "Nausea, diarrhea, stomach pain, headache. Rare: cardiac rhythm changes.",
        "dosage": "500mg once daily for 3–5 days (adults). Take on empty stomach or with food if stomach upset.",
        "precautions": "Complete the full course. Can interact with antacids (take 2 hours apart).",
        "contraindications": "Liver disease, QT prolongation disorders, allergy to macrolides.",
        "is_otc": False,
        "emoji": "💊",
    },
    {
        "name": "Ciprofloxacin",
        "brand_names": "Ciplox, Cifran, Cipro",
        "category": "Antibiotics",
        "medicine_type": "Tablet",
        "active_ingredients": "Ciprofloxacin 250mg, 500mg",
        "uses": "Fluoroquinolone antibiotic. Treats UTIs, typhoid, respiratory infections, bone/joint infections, anthrax exposure.",
        "side_effects": "Nausea, diarrhea, headache, dizziness. Risk of tendon rupture (rare). Can worsen myasthenia gravis.",
        "dosage": "250–750mg twice daily for 7–14 days depending on infection.",
        "precautions": "Avoid excessive sun exposure (photosensitivity). Avoid antacids within 2 hours. Stay hydrated.",
        "contraindications": "Children and adolescents (growing bones), pregnancy, myasthenia gravis.",
        "is_otc": False,
        "emoji": "💊",
    },
    {
        "name": "Metronidazole",
        "brand_names": "Flagyl, Metrogyl, Aldezole, Metro",
        "category": "Antibiotics",
        "medicine_type": "Tablet / Suspension / IV",
        "active_ingredients": "Metronidazole 200mg, 400mg, 500mg",
        "uses": "Antibiotic and antiprotozoal. Treats bacterial vaginal infections, dental infections, H. pylori (stomach ulcer), giardia, amoebiasis, C. difficile.",
        "side_effects": "Metallic taste, nausea, vomiting, headache, dark urine.",
        "dosage": "400–500mg three times daily for 5–7 days. Take with or after food.",
        "precautions": "ABSOLUTELY do not drink alcohol during treatment and for 48 hours after (causes severe vomiting).",
        "contraindications": "First trimester of pregnancy, alcohol consumption, severe liver disease.",
        "is_otc": False,
        "emoji": "💊",
    },
    {
        "name": "Doxycycline",
        "brand_names": "Doxt, Vibramycin, Doxirobe",
        "category": "Antibiotics",
        "medicine_type": "Tablet / Capsule",
        "active_ingredients": "Doxycycline Hyclate 100mg",
        "uses": "Broad-spectrum antibiotic. Treats malaria prevention, acne, Lyme disease, chlamydia, respiratory infections, cholera.",
        "side_effects": "Nausea, photosensitivity (sun sensitivity), esophageal irritation if not swallowed with water.",
        "dosage": "100mg twice daily or 200mg once daily. Take upright with a full glass of water. Do not lie down for 30 min after.",
        "precautions": "Avoid direct sunlight — use sunscreen. Do not take with milk, antacids, or iron within 2 hours.",
        "contraindications": "Children under 8 (stains developing teeth), pregnancy, breastfeeding.",
        "is_otc": False,
        "emoji": "💊",
    },

    # ─────────────────────────────────────────────────────────────
    # VITAMINS & SUPPLEMENTS
    # ─────────────────────────────────────────────────────────────
    {
        "name": "Vitamin C (Ascorbic Acid)",
        "brand_names": "Limcee, Celin, Redoxon, Ester-C",
        "category": "Vitamins & Supplements",
        "medicine_type": "Tablet / Chewable Tablet",
        "active_ingredients": "Ascorbic Acid 500mg or 1000mg",
        "uses": "Prevents and treats Vitamin C deficiency (scurvy). Boosts immune function. Antioxidant. Helps iron absorption. Supports wound healing and skin health.",
        "side_effects": "Generally safe. High doses (>2g/day): stomach upset, diarrhea, kidney stones.",
        "dosage": "RDA: 65–90mg/day. For immunity support: 500–1000mg daily. Chew or dissolve in water.",
        "precautions": "High doses can interfere with certain lab tests. Take with food to reduce stomach upset.",
        "contraindications": "History of kidney stones with high doses. G6PD deficiency (high doses).",
        "is_otc": True,
        "emoji": "🍊",
    },
    {
        "name": "Vitamin D3 (Cholecalciferol)",
        "brand_names": "Calcirol, Uprise-D3, Sunshine D3, Calshine",
        "category": "Vitamins & Supplements",
        "medicine_type": "Tablet / Sachet / Drops",
        "active_ingredients": "Cholecalciferol (Vitamin D3) 1000 IU, 2000 IU, 60000 IU",
        "uses": "Treats and prevents Vitamin D deficiency. Supports bone health, calcium absorption, immune function, mood, and muscle strength.",
        "side_effects": "Safe at normal doses. Toxicity with very high doses: nausea, weakness, kidney damage, calcium buildup.",
        "dosage": "Deficiency treatment: 60,000 IU weekly for 8–12 weeks (doctor prescribed). Maintenance: 1000–2000 IU daily.",
        "precautions": "Fat-soluble — take with a fatty meal. Blood levels should be monitored during treatment.",
        "contraindications": "Hypercalcemia, sarcoidosis, overactive parathyroid gland.",
        "is_otc": True,
        "emoji": "☀️",
    },
    {
        "name": "Vitamin B12 (Cobalamin)",
        "brand_names": "Methylcobalamin, Neurobin, Cobadex, Megabol",
        "category": "Vitamins & Supplements",
        "medicine_type": "Tablet / Injection",
        "active_ingredients": "Methylcobalamin or Cyanocobalamin 500mcg, 1000mcg, 1500mcg",
        "uses": "Treats B12 deficiency. Essential for nerve health, red blood cell production, DNA synthesis, and brain function. Prevents pernicious anemia.",
        "side_effects": "Very safe. Rare: mild diarrhea, itching. Injection site reactions.",
        "dosage": "500–1500mcg daily (oral). Severe deficiency: 1000mcg injection weekly (prescribed).",
        "precautions": "Vegans and vegetarians are at high risk of deficiency. Elderly people absorb it poorly.",
        "contraindications": "Allergy to cobalamin or cobalt. Leber's disease (cyanocobalamin form only).",
        "is_otc": True,
        "emoji": "💊",
    },
    {
        "name": "Folic Acid (Vitamin B9)",
        "brand_names": "Folvite, Folifort, Ecofol",
        "category": "Vitamins & Supplements",
        "medicine_type": "Tablet",
        "active_ingredients": "Folic Acid 0.4mg (400mcg), 1mg, 5mg",
        "uses": "Essential during pregnancy to prevent neural tube defects (spina bifida). Treats megaloblastic anemia. Supports cell division and DNA synthesis.",
        "side_effects": "Generally very safe. Can mask B12 deficiency at high doses.",
        "dosage": "Pregnancy prevention: 400mcg daily starting 3 months before conception. Deficiency treatment: 5mg daily (prescribed).",
        "precautions": "All women of childbearing age should take 400mcg daily. Can mask symptoms of B12 deficiency.",
        "contraindications": "Undiagnosed anemia (should test for B12 first).",
        "is_otc": True,
        "emoji": "🌿",
    },
    {
        "name": "Iron Supplements (Ferrous Sulfate / Ferrous Fumarate)",
        "brand_names": "Feosol, Livogen, Autrin, Hemfer",
        "category": "Vitamins & Supplements",
        "medicine_type": "Tablet / Syrup",
        "active_ingredients": "Ferrous Sulfate 200mg (65mg elemental iron) or Ferrous Fumarate 200mg",
        "uses": "Treats iron deficiency anemia. Used in pregnancy for iron supplementation.",
        "side_effects": "Constipation, dark/black stools (normal), nausea, stomach cramps. Take with Vitamin C to improve absorption.",
        "dosage": "One tablet (65mg elemental iron) twice or three times daily on empty stomach or with Vitamin C.",
        "precautions": "Black stools are normal. Store away from children (iron overdose is dangerous). May stain teeth (use straw for liquid form).",
        "contraindications": "Hemochromatosis (iron overload), hemolytic anemia, repeated blood transfusions.",
        "is_otc": True,
        "emoji": "💊",
    },
    {
        "name": "Calcium + Vitamin D3",
        "brand_names": "Shelcal, Calcitas, Ossovit, Caltrate",
        "category": "Vitamins & Supplements",
        "medicine_type": "Tablet / Chewable",
        "active_ingredients": "Calcium Carbonate 500–1250mg + Cholecalciferol (Vitamin D3) 250–500 IU",
        "uses": "Prevents and treats calcium deficiency. Supports bone strength, prevents osteoporosis. Treats rickets and hypocalcemia.",
        "side_effects": "Constipation, bloating, nausea, excessive calcium with very high doses (kidney stones).",
        "dosage": "500–1000mg calcium daily, split into 2 doses with meals for best absorption.",
        "precautions": "Take with meals (calcium carbonate needs stomach acid). Split doses — body absorbs max ~500mg at once.",
        "contraindications": "Hypercalcemia, kidney stones (certain types), sarcoidosis.",
        "is_otc": True,
        "emoji": "🦴",
    },
    {
        "name": "Zinc Supplement",
        "brand_names": "Zincovit, Zincolak, Zevit, Zinconia",
        "category": "Vitamins & Supplements",
        "medicine_type": "Tablet / Syrup",
        "active_ingredients": "Zinc Sulfate or Zinc Gluconate 10mg–50mg elemental zinc",
        "uses": "Treats zinc deficiency. Boosts immune function. Reduces duration and severity of common cold. Supports wound healing, taste, and smell.",
        "side_effects": "Nausea, vomiting, stomach upset (at high doses). Long-term high doses deplete copper.",
        "dosage": "RDA: 8–11mg/day. Therapeutic: 25–50mg/day with food. Children with diarrhea: 10–20mg daily for 10–14 days.",
        "precautions": "Take with food to reduce nausea. Do not exceed 40mg/day long-term without medical supervision.",
        "contraindications": "High doses interfere with copper and iron absorption.",
        "is_otc": True,
        "emoji": "💊",
    },
    {
        "name": "Omega-3 Fatty Acids (Fish Oil)",
        "brand_names": "Seven Seas, Wiley's Finest, Epax, Megared",
        "category": "Vitamins & Supplements",
        "medicine_type": "Soft Gel Capsule",
        "active_ingredients": "EPA (Eicosapentaenoic acid) + DHA (Docosahexaenoic acid) — combined ~1000mg",
        "uses": "Reduces triglycerides. Supports heart health and brain function. Anti-inflammatory. Helpful in depression, dry eyes, and joint inflammation.",
        "side_effects": "Fishy aftertaste or burps. Nausea, loose stools. High doses thin the blood.",
        "dosage": "1000–3000mg daily with food. Heart health: 2–4g/day EPA+DHA (prescribed).",
        "precautions": "Take with meals to reduce fishy burps. High doses may increase bleeding risk.",
        "contraindications": "Fish or shellfish allergy. Bleeding disorders (high doses).",
        "is_otc": True,
        "emoji": "🐟",
    },

    # ─────────────────────────────────────────────────────────────
    # CARDIOVASCULAR
    # ─────────────────────────────────────────────────────────────
    {
        "name": "Atorvastatin",
        "brand_names": "Lipitor, Atorva, Torvastat",
        "category": "Cardiovascular",
        "medicine_type": "Tablet",
        "active_ingredients": "Atorvastatin 10mg, 20mg, 40mg, 80mg",
        "uses": "Lowers LDL (bad) cholesterol and triglycerides. Reduces risk of heart attack, stroke, and angina.",
        "side_effects": "Muscle pain/weakness (myopathy), liver enzyme elevation, headache, nausea, blood sugar changes.",
        "dosage": "10–80mg once daily, usually at bedtime.",
        "precautions": "Report unexplained muscle pain or weakness immediately. Avoid grapefruit juice.",
        "contraindications": "Liver disease, pregnancy, breastfeeding, unexplained muscle problems.",
        "is_otc": False,
        "emoji": "❤️",
    },
    {
        "name": "Amlodipine",
        "brand_names": "Amlip, Stamlo, Norvasc",
        "category": "Cardiovascular",
        "medicine_type": "Tablet",
        "active_ingredients": "Amlodipine Besylate 2.5mg, 5mg, 10mg",
        "uses": "Calcium channel blocker. Treats high blood pressure (hypertension) and angina (chest pain).",
        "side_effects": "Ankle swelling (oedema), flushing, headache, dizziness, fatigue.",
        "dosage": "5–10mg once daily. Can be taken at any time of day.",
        "precautions": "Do not stop abruptly. Monitor blood pressure. Rise slowly from sitting position.",
        "contraindications": "Severe hypotension (low blood pressure), aortic stenosis, cardiogenic shock.",
        "is_otc": False,
        "emoji": "❤️",
    },

    # ─────────────────────────────────────────────────────────────
    # DIABETES
    # ─────────────────────────────────────────────────────────────
    {
        "name": "Metformin",
        "brand_names": "Glycomet, Glucophage, Obimet",
        "category": "Diabetes",
        "medicine_type": "Tablet",
        "active_ingredients": "Metformin HCl 500mg, 850mg, 1000mg",
        "uses": "First-line treatment for Type 2 Diabetes. Lowers blood sugar by reducing liver glucose production and improving insulin sensitivity.",
        "side_effects": "Nausea, diarrhea, stomach upset (mostly when starting). Very rarely: lactic acidosis.",
        "dosage": "Start 500mg twice daily with meals, gradually increase. Max 2550mg/day.",
        "precautions": "Take with food to reduce GI side effects. Hold before CT scans with contrast dye. Monitor kidney function.",
        "contraindications": "Severe kidney disease (eGFR <30), liver disease, heart failure, heavy alcohol use.",
        "is_otc": False,
        "emoji": "🩸",
    },

    # ─────────────────────────────────────────────────────────────
    # ANTIFUNGAL & ANTIPARASITIC
    # ─────────────────────────────────────────────────────────────
    {
        "name": "Clotrimazole",
        "brand_names": "Canesten, Clotri, Candid, Fungicide",
        "category": "Antifungal",
        "medicine_type": "Cream / Powder / Pessary",
        "active_ingredients": "Clotrimazole 1%",
        "uses": "Treats fungal skin infections: ringworm (dermatophytosis), athlete's foot, jock itch, vaginal thrush (Candida), pityriasis versicolor.",
        "side_effects": "Mild burning, stinging, or redness on application. Very rare allergic reaction.",
        "dosage": "Apply thin layer to affected skin 2–3 times daily for 2–4 weeks. Continue for 2 weeks after skin appears clear.",
        "precautions": "For external use only (cream). Keep skin dry. Continue full course to prevent recurrence.",
        "contraindications": "Allergy to clotrimazole. Do not use in eyes.",
        "is_otc": True,
        "emoji": "🍄",
    },
    {
        "name": "Albendazole",
        "brand_names": "Zentel, Noworm, Albenza",
        "category": "Antifungal",
        "medicine_type": "Tablet / Syrup",
        "active_ingredients": "Albendazole 400mg",
        "uses": "Treats intestinal worm infections: roundworm, pinworm, hookworm, whipworm, tapeworm, giardia.",
        "side_effects": "Nausea, abdominal pain, headache, dizziness. Liver enzyme elevation with long-term use.",
        "dosage": "Single dose of 400mg for most worm infections. Take with food (fatty meal increases absorption).",
        "precautions": "May need a second dose after 2 weeks for pinworm. Treat all household contacts.",
        "contraindications": "Pregnancy (especially first trimester), allergy to albendazole.",
        "is_otc": True,
        "emoji": "💊",
    },

    # ─────────────────────────────────────────────────────────────
    # EYE & EAR
    # ─────────────────────────────────────────────────────────────
    {
        "name": "Ciprofloxacin Eye/Ear Drops",
        "brand_names": "Ciplox Eye Drops, Ciloxan",
        "category": "Eye & Ear",
        "medicine_type": "Eye Drops / Ear Drops",
        "active_ingredients": "Ciprofloxacin 0.3%",
        "uses": "Treats bacterial eye infections (conjunctivitis, corneal ulcers) and bacterial ear infections (otitis externa).",
        "side_effects": "Mild stinging or burning on instillation. Taste in mouth after eye drops (normal — nasolacrimal drainage).",
        "dosage": "Eyes: 1–2 drops every 2–4 hours for 2 days, then every 4 hours for 5 more days. Ears: 3–4 drops twice daily for 7 days.",
        "precautions": "Do not touch dropper tip to eye/ear. Tilt head and press corner of eye after drops. Discard 4 weeks after opening.",
        "contraindications": "Allergy to ciprofloxacin or quinolones. Perforated eardrum (ear drops).",
        "is_otc": False,
        "emoji": "👁️",
    },
    {
        "name": "Artificial Tears / Lubricating Eye Drops",
        "brand_names": "Refresh Tears, Systane, Genteal, Tears Naturale, I-Lube",
        "category": "Eye & Ear",
        "medicine_type": "Eye Drops",
        "active_ingredients": "Carboxymethylcellulose (CMC) 0.5% or 1%, or Hydroxypropyl Methylcellulose (HPMC)",
        "uses": "Relieves dry, irritated, and tired eyes. Reduces redness and discomfort from dry eye syndrome, environmental irritants, or prolonged screen use.",
        "side_effects": "Temporary blurred vision immediately after use (normal). Mild stinging.",
        "dosage": "1–2 drops in each eye as needed, up to 4–6 times per day. Preservative-free versions can be used more frequently.",
        "precautions": "Preservative-containing drops: limit to 4× daily. Remove contact lenses before use, wait 15 min to reinsert.",
        "contraindications": "Allergy to any ingredient. Do not use for eye infections (masks symptoms).",
        "is_otc": True,
        "emoji": "👁️",
    },

    # ─────────────────────────────────────────────────────────────
    # SKIN CARE
    # ─────────────────────────────────────────────────────────────
    {
        "name": "Hydrocortisone Cream",
        "brand_names": "Cortisyl, Hycort, Dermacort, HC Cream",
        "category": "Skin Care",
        "medicine_type": "Topical Cream",
        "active_ingredients": "Hydrocortisone 1%",
        "uses": "Mild corticosteroid. Relieves itching, redness, and inflammation from eczema, dermatitis, insect bites, mild psoriasis, nappy rash.",
        "side_effects": "Skin thinning with prolonged use, stretch marks, increased skin infections, local burning.",
        "dosage": "Apply a thin layer to affected area 1–2 times daily. Use for a maximum of 7 days on face, 2 weeks on body.",
        "precautions": "Do not use on face for more than 1 week. Do not use on broken/infected skin. Not for use near eyes.",
        "contraindications": "Infected skin (bacterial/fungal/viral), rosacea, acne, skin around eyes (long-term).",
        "is_otc": True,
        "emoji": "🧴",
    },
    {
        "name": "Mupirocin (Bactroban)",
        "brand_names": "Bactroban, Mupiderm, T-Bact",
        "category": "Skin Care",
        "medicine_type": "Topical Ointment / Cream",
        "active_ingredients": "Mupirocin 2%",
        "uses": "Treats bacterial skin infections: impetigo, infected wounds, folliculitis (infected hair follicles), skin infections caused by Staph/Strep.",
        "side_effects": "Burning, stinging, or itching at application site. Rare: allergic contact dermatitis.",
        "dosage": "Apply small amount to affected area 2–3 times daily for 5–10 days. Cover with dressing if needed.",
        "precautions": "Avoid contact with eyes. For external use only. Do not use for more than 10 days.",
        "contraindications": "Allergy to mupirocin or polyethylene glycol (in ointment base).",
        "is_otc": False,
        "emoji": "🧴",
    },

    # ─────────────────────────────────────────────────────────────
    # MENTAL HEALTH & SLEEP
    # ─────────────────────────────────────────────────────────────
    {
        "name": "Melatonin",
        "brand_names": "Meloset, Slenyto, Circadin",
        "category": "Mental Health & Sleep",
        "medicine_type": "Tablet",
        "active_ingredients": "Melatonin 0.5mg, 1mg, 3mg, 5mg",
        "uses": "Treats insomnia and sleep disorders. Helps adjust sleep-wake cycle for jet lag and shift workers. Non-addictive.",
        "side_effects": "Drowsiness, headache, dizziness, nausea. Daytime grogginess if taken too close to wake time.",
        "dosage": "0.5–5mg taken 30–60 minutes before bedtime. Start with lowest effective dose.",
        "precautions": "Do not drive after taking. Avoid alcohol. May interact with blood thinners and birth control.",
        "contraindications": "Autoimmune conditions. Pregnancy and breastfeeding. Children — use only under doctor guidance.",
        "is_otc": True,
        "emoji": "🌙",
    },
]


async def seed():
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    async with AsyncSessionLocal() as session:
        # Check if already seeded
        result = await session.execute(select(Medicine).limit(1))
        existing = result.scalars().first()
        if existing:
            print(f"Database already has medicines. Skipping seed.")
            return

        print(f"Seeding {len(MEDICINES)} medicines...")
        for m in MEDICINES:
            session.add(Medicine(**m))
        await session.commit()
        print("✅ Medicine database seeded successfully!")


if __name__ == "__main__":
    asyncio.run(seed())
